# Generated by Django 2.1.5 on 2019-10-21 18:27

import datetime

import django.db.models.deletion
from django.db import migrations, models

import archive.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Hinzugefügt am')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Titel')),
                ('firstname', models.CharField(blank=True, max_length=256, null=True, verbose_name='Vorname')),
                ('lastname', models.CharField(max_length=256, verbose_name='Nachname *')),
                ('filepath', models.SlugField(blank=True, null=True, unique=True,
                                              verbose_name='Pfad wo die Dateien abgelegt werden (wird automatisch berechnet beim Speichern)')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autoren',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Hinzugefügt am')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
                ('title', models.CharField(max_length=1024, verbose_name='Titel *')),
                ('medart', models.CharField(
                    choices=[('Artikel', 'Artikel'), ('Audiodatei', 'Audiodatei'), ('Buch', 'Buch'),
                             ('CD / DVD', 'CD / DVD'), ('Dia(s)', 'Dia(s)'), ('Filmspule', 'Filmspule'),
                             ('Foto(s)', 'Foto(s)'), ('Gegenstand', 'Gegenstand'), ('Kassette', 'Kassette'),
                             ('Schallplatte', 'Schallplatte'), ('Schrifttum', 'Schrifttum'), ('Sonstiges', 'Sonstiges'),
                             ('Stempel', 'Stempel'), ('Tonband', 'Tonband'), ('VHS', 'VHS'),
                             ('Videodatei', 'Videodatei')], max_length=256, verbose_name='Medienart *')),
                ('source_title', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Quelltitel')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Abstract')),
                ('year', models.IntegerField(blank=True, default=2019, null=True, verbose_name='Jahrgang')),
                ('pages', models.CharField(blank=True, max_length=256, null=True, verbose_name='Seiten')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Anmerkungen')),
                ('place',
                 models.CharField(blank=True, max_length=256, null=True, verbose_name='Ort / Veröffentlichung')),
                ('keywords',
                 models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='Schlagworte')),
                ('location',
                 models.CharField(blank=True, max_length=256, null=True, verbose_name='Standort (analoges Archiv)')),
                ('amount', models.IntegerField(blank=True, default=1, null=True, verbose_name='Anzahl / Exemplare')),
                ('public', models.BooleanField(default=True, verbose_name='Veröffentlichen?')),
                ('digital_reference', models.URLField(blank=True, null=True, verbose_name='Digitalreferenz (URL)')),
                ('file1', models.FileField(blank=True, null=True, upload_to=archive.models.construct_file_path,
                                           verbose_name='1. Datei')),
                ('file2', models.FileField(blank=True, null=True, upload_to=archive.models.construct_file_path,
                                           verbose_name='2. Datei')),
                ('file3', models.FileField(blank=True, null=True, upload_to=archive.models.construct_file_path,
                                           verbose_name='3. Datei')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=archive.models.construct_file_path,
                                             verbose_name='1. Abbildung')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=archive.models.construct_file_path,
                                             verbose_name='2. Abbildung')),
                ('image3', models.ImageField(blank=True, null=True, upload_to=archive.models.construct_file_path,
                                             verbose_name='3. Abbildung')),
                ('author',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.Author')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
